"""producto independiente por sucursal

Revision ID: 091c63ac5145
Revises: b6c4d6ad9596
Create Date: 2026-09-10 10:25:38.054398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091c63ac5145'
down_revision: Union[str, Sequence[str], None] = 'b6c4d6ad9596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Agregar sucursal_id temporalmente permitiendo NULL
    op.add_column(
        "productos",
        sa.Column("sucursal_id", sa.BigInteger(), nullable=True)
    )

    # 2. El código deja de ser único globalmente
    op.drop_constraint(
        "productos_codigo_key",
        "productos",
        type_="unique"
    )

    # 3. Asignar al producto original una de las sucursales
    #    en las que actualmente tiene inventario
    op.execute("""
        UPDATE productos AS p
        SET sucursal_id = datos.sucursal_id
        FROM (
            SELECT producto_id, MIN(sucursal_id) AS sucursal_id
            FROM inventarios
            GROUP BY producto_id
        ) AS datos
        WHERE p.id = datos.producto_id;
    """)

    # 4. Si un mismo producto estaba en varias sucursales,
    #    crear una copia independiente para cada sucursal adicional
    op.execute("""
        DO $$
        DECLARE
            registro RECORD;
            nuevo_producto_id BIGINT;
        BEGIN
            FOR registro IN
                SELECT
                    p.id AS producto_id_original,
                    i.sucursal_id
                FROM productos p
                JOIN inventarios i
                    ON i.producto_id = p.id
                WHERE i.sucursal_id <> p.sucursal_id
                GROUP BY p.id, i.sucursal_id
            LOOP

                INSERT INTO productos (
                    created_at,
                    codigo,
                    nombre,
                    precio,
                    iva,
                    categoria_id,
                    activo,
                    sucursal_id
                )
                SELECT
                    created_at,
                    codigo,
                    nombre,
                    precio,
                    iva,
                    categoria_id,
                    activo,
                    registro.sucursal_id
                FROM productos
                WHERE id = registro.producto_id_original
                RETURNING id INTO nuevo_producto_id;

                UPDATE inventarios
                SET producto_id = nuevo_producto_id
                WHERE producto_id = registro.producto_id_original
                AND sucursal_id = registro.sucursal_id;

            END LOOP;
        END $$;
    """)

    # 5. Los productos de prueba que no tienen inventario
    #    se asignan a la sucursal 1 para conservarlos
    op.execute("""
        UPDATE productos
        SET sucursal_id = 1
        WHERE sucursal_id IS NULL;
    """)

    # 6. Detener la migración si existe algún producto
    #    que no pudo asociarse a ninguna sucursal
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM productos
                WHERE sucursal_id IS NULL
            ) THEN
                RAISE EXCEPTION
                'Existen productos sin inventario y no se puede determinar su sucursal';
            END IF;
        END $$;
    """)

    # 6. Ahora sí sucursal_id es obligatorio
    op.alter_column(
        "productos",
        "sucursal_id",
        existing_type=sa.BigInteger(),
        nullable=False
    )

    # 7. Relación producto -> sucursal
    op.create_foreign_key(
        "fk_productos_sucursal_id",
        "productos",
        "sucursales",
        ["sucursal_id"],
        ["id"]
    )

    # 8. El código es único solamente dentro de una sucursal
    op.create_unique_constraint(
        "uq_productos_sucursal_codigo",
        "productos",
        ["sucursal_id", "codigo"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_productos_sucursal_id', 'productos', type_='foreignkey')
    op.drop_constraint('uq_productos_sucursal_codigo', 'productos', type_='unique')
    op.create_unique_constraint('productos_codigo_key', 'productos', ['codigo'])
    op.drop_column('productos', 'sucursal_id')

    # ### end Alembic commands ###
