"""ajustes modelos sprint 3

Revision ID: b6c4d6ad9596
Revises: be2f873c9a46
Create Date: 2026-09-07 20:03:15.041987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6c4d6ad9596'
down_revision: Union[str, Sequence[str], None] = 'be2f873c9a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sucursal_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('existencia', sa.BigInteger(), nullable=False),
    sa.Column('stock_minimo', sa.BigInteger(), nullable=False),
    sa.Column('actualizado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('existencia >= 0', name='ck_inventarios_existencia_no_negativa'),
    sa.CheckConstraint('stock_minimo >= 0', name='ck_inventarios_stock_minimo_no_negativo'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id', 'producto_id', name='uq_inventarios_sucursal_producto')
    )
    op.create_index(op.f('ix_inventarios_id'), 'inventarios', ['id'], unique=False)
    op.create_index(op.f('ix_inventarios_producto_id'), 'inventarios', ['producto_id'], unique=False)
    op.create_index(op.f('ix_inventarios_sucursal_id'), 'inventarios', ['sucursal_id'], unique=False)
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.drop_table('inventario')
    op.alter_column('productos', 'precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('productos', 'iva',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sucursales', 'telefono',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'sucursales', ['gerente_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sucursales', type_='unique')
    op.alter_column('sucursales', 'telefono',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('productos', 'iva',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('productos', 'precio',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_table('inventario',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sucursal_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stock_minimo', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('cantidad >= 0', name=op.f('ck_inventario_cantidad_no_negativa')),
    sa.CheckConstraint('stock_minimo >= 0', name=op.f('ck_inventario_stock_minimo_no_negativo')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('inventario_producto_id_fkey')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], name=op.f('inventario_sucursal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventario_pkey')),
    sa.UniqueConstraint('sucursal_id', 'producto_id', name=op.f('uq_inventario_sucursal_producto'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.drop_index(op.f('ix_inventarios_sucursal_id'), table_name='inventarios')
    op.drop_index(op.f('ix_inventarios_producto_id'), table_name='inventarios')
    op.drop_index(op.f('ix_inventarios_id'), table_name='inventarios')
    op.drop_table('inventarios')
    # ### end Alembic commands ###
